services:
  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000 from container to host
    volumes:
      - .:/app  # Mount the local directory into the container (for dev)
    command: ["pnpm", "run", "dev", "--port", "8000"]
